import type { PriorityLevel, RefreshQuota } from "./dashboard-brief-types";

/**
 * Shared briefing API types and sanitizers, used on both the client
 * (response guard) and the server (AI output + stored-row guard).
 */

export const BRIEFING_CATEGORIES = [
  "email",
  "messages",
  "mentions",
  "tasks",
  "follow_ups",
] as const;

export type BriefingCategoryId = (typeof BRIEFING_CATEGORIES)[number];

export const BRIEFING_FREQUENCIES = [
  "daily",
  "weekdays",
  "weekly",
  "once",
] as const;

export type BriefingFrequency = (typeof BRIEFING_FREQUENCIES)[number];

/** URL slug (kebab-case) for a category id (snake_case). */
export function categorySlug(id: BriefingCategoryId): string {
  return id.replaceAll("_", "-");
}

export function categoryFromSlug(slug: string): BriefingCategoryId | null {
  const id = slug.replaceAll("-", "_");
  return (BRIEFING_CATEGORIES as readonly string[]).includes(id)
    ? (id as BriefingCategoryId)
    : null;
}

export type BriefingItem = {
  /** Stable within one generated briefing (assigned by the sanitizer). */
  id: string;
  /** Provider id, e.g. "gmail". */
  source: string;
  title: string;
  description: string;
  priority: PriorityLevel;
  /** ISO timestamp of the underlying item; may be empty when unknown. */
  timestamp: string;
  /** Deep link to the underlying item (e.g. the email in Gmail). */
  link?: string;
  /**
   * Source-item id echoed by the AI; the service resolves it to `link` and
   * strips it, so it never appears in API responses or stored rows.
   */
  ref?: string;
};

export type BriefingCategory = {
  count: number;
  summary: string;
  items: BriefingItem[];
};

export type BriefingCategories = Partial<
  Record<BriefingCategoryId, BriefingCategory>
>;

/** The generated payload persisted in briefing_results.data. */
export type BriefingResultData = {
  /** The highlighted "top brief" summary of the day. */
  topSummary: string;
  categories: BriefingCategories;
  priorityItems: BriefingItem[];
  /** Provider ids that contributed data. */
  sources: string[];
  /** True when the AI was unavailable and the result was built mechanically. */
  degraded: boolean;
  /** True when at least one selected provider failed or timed out. */
  partial?: boolean;
  generatedAt: string;
};

/** The subset the AI generates; the service fills in the rest. */
export type AiBriefingResult = Pick<
  BriefingResultData,
  "topSummary" | "categories" | "priorityItems"
>;

/** A generated briefing as returned by the API (result row + identity). */
export type GeneratedBriefing = BriefingResultData & {
  id: string;
  /** Owning definition; null only for rows whose definition was deleted. */
  briefingId: string | null;
  /** True when generated by the automatic daily brief. */
  isDefault: boolean;
  title: string;
};

export type GeneratedBriefingSummary = {
  id: string;
  briefingId: string | null;
  isDefault: boolean;
  title: string;
  generatedAt: string;
  totalCount: number;
  degraded: boolean;
};

export type BriefingDefinition = {
  id: string;
  name: string;
  description: string;
  isDefault: boolean;
  /** Provider ids; empty = every connected provider. */
  apps: string[];
  categories: BriefingCategoryId[];
  priority: PriorityLevel;
  frequency: BriefingFrequency;
  /** "HH:MM" local wall clock in `timezone`. */
  scheduleTime: string;
  /** IANA zone name. */
  timezone: string;
  /** Only for frequency "once". */
  runAt?: string;
  enabled: boolean;
  nextRunAt: string | null;
  createdAt: string;
  lastGeneratedAt?: string;
};

export type BriefingDefinitionInput = {
  name: string;
  description: string;
  apps: string[];
  categories: BriefingCategoryId[];
  priority: PriorityLevel;
  frequency: BriefingFrequency;
  scheduleTime: string;
  timezone: string;
  runAt?: string;
};

/** The hub page payload (single fetch). */
export type BriefingsOverview = {
  today: GeneratedBriefing | null;
  configs: BriefingDefinition[];
  history: GeneratedBriefingSummary[];
  refresh?: RefreshQuota;
};

const PRIORITY_LEVELS: readonly string[] = ["low", "medium", "high"];

const MAX_ITEMS_PER_CATEGORY = 8;
const MAX_PRIORITY_ITEMS = 5;

function clampCount(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value)
    ? Math.max(0, Math.trunc(value))
    : 0;
}

function cut(value: unknown, max: number): string {
  const text = typeof value === "string" ? value.trim() : "";
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

function parseItems(
  value: unknown,
  idPrefix: string,
  max: number,
  valid?: readonly string[],
): BriefingItem[] {
  return (Array.isArray(value) ? value : [])
    .flatMap((item): Omit<BriefingItem, "id">[] => {
      if (!item || typeof item !== "object") return [];
      const { source, title, description, priority, timestamp, link, ref } =
        item as Record<string, unknown>;
      const heading = cut(title, 120);
      const app =
        typeof source === "string" && source && (!valid || valid.includes(source))
          ? source
          : null;
      if (!app || !heading) return [];
      const time = cut(timestamp, 40);
      const safeLink =
        typeof link === "string" && /^https:\/\//.test(link)
          ? cut(link, 400)
          : undefined;
      const safeRef = cut(ref, 64) || undefined;
      return [
        {
          source: app,
          title: heading,
          description: cut(description, 300),
          priority: PRIORITY_LEVELS.includes(priority as string)
            ? (priority as PriorityLevel)
            : "medium",
          timestamp: Number.isNaN(Date.parse(time)) ? "" : time,
          ...(safeLink ? { link: safeLink } : {}),
          ...(safeRef ? { ref: safeRef } : {}),
        },
      ];
    })
    .slice(0, max)
    .map((item, index) => ({ id: `${idPrefix}-${index}`, ...item }));
}

function parseCategories(
  value: unknown,
  requested?: readonly BriefingCategoryId[],
  valid?: readonly string[],
): BriefingCategories {
  if (!value || typeof value !== "object") return {};
  const raw = value as Record<string, unknown>;
  const keys = requested ?? BRIEFING_CATEGORIES;
  const categories: BriefingCategories = {};
  for (const key of keys) {
    const entry = raw[key];
    if (!entry || typeof entry !== "object") continue;
    const { count, summary, items } = entry as Record<string, unknown>;
    categories[key] = {
      count: clampCount(count),
      summary: cut(summary, 200),
      items: parseItems(items, key, MAX_ITEMS_PER_CATEGORY, valid),
    };
  }
  return categories;
}

/**
 * Narrows untrusted AI output into the AI-generated subset of a briefing.
 * Only requested category keys survive; counts are clamped (and later
 * overridden mechanically by the service where possible).
 */
export function sanitizeAiBriefingResult(
  value: unknown,
  validSources: readonly string[],
  requestedCategories: readonly BriefingCategoryId[],
): AiBriefingResult | null {
  if (!value || typeof value !== "object") return null;
  const raw = value as Record<string, unknown>;
  const topSummary = cut(raw.topSummary, 300);
  if (!topSummary) return null;
  return {
    topSummary,
    categories: parseCategories(raw.categories, requestedCategories, validSources),
    priorityItems: parseItems(
      raw.priorityItems,
      "priority",
      MAX_PRIORITY_ITEMS,
      validSources,
    ),
  };
}

function parseSources(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((s): s is string => typeof s === "string" && s.length > 0);
}

/**
 * Narrows a full untrusted result payload (stored row or API response).
 * Strict on topSummary/generatedAt so rows in older shapes are rejected.
 */
export function sanitizeBriefingResult(value: unknown): BriefingResultData | null {
  if (!value || typeof value !== "object") return null;
  const raw = value as Record<string, unknown>;
  const topSummary = cut(raw.topSummary, 300);
  if (!topSummary) return null;
  if (typeof raw.generatedAt !== "string" || !raw.generatedAt) return null;
  return {
    topSummary,
    categories: parseCategories(raw.categories),
    priorityItems: parseItems(raw.priorityItems, "priority", MAX_PRIORITY_ITEMS),
    sources: parseSources(raw.sources),
    degraded: raw.degraded === true,
    partial: raw.partial === true,
    generatedAt: raw.generatedAt,
  };
}

/** Client-side guard for a GeneratedBriefing API payload. */
export function sanitizeGeneratedBriefing(value: unknown): GeneratedBriefing | null {
  if (!value || typeof value !== "object") return null;
  const raw = value as Record<string, unknown>;
  if (typeof raw.id !== "string" || !raw.id) return null;
  const data = sanitizeBriefingResult(value);
  if (!data) return null;
  return {
    ...data,
    id: raw.id,
    briefingId: typeof raw.briefingId === "string" ? raw.briefingId : null,
    isDefault: raw.isDefault === true,
    title: cut(raw.title, 80) || "Briefing",
  };
}

export function sanitizeBriefingSummaries(
  value: unknown,
): GeneratedBriefingSummary[] {
  return (Array.isArray(value) ? value : []).flatMap(
    (entry): GeneratedBriefingSummary[] => {
      if (!entry || typeof entry !== "object") return [];
      const raw = entry as Record<string, unknown>;
      if (typeof raw.id !== "string" || !raw.id) return [];
      if (typeof raw.generatedAt !== "string" || !raw.generatedAt) return [];
      return [
        {
          id: raw.id,
          briefingId: typeof raw.briefingId === "string" ? raw.briefingId : null,
          isDefault: raw.isDefault === true,
          title: cut(raw.title, 80) || "Briefing",
          generatedAt: raw.generatedAt,
          totalCount: clampCount(raw.totalCount),
          degraded: raw.degraded === true,
        },
      ];
    },
  );
}

/** Guard for a definition row coming over the API. */
export function sanitizeBriefingDefinition(
  value: unknown,
): BriefingDefinition | null {
  if (!value || typeof value !== "object") return null;
  const raw = value as Record<string, unknown>;
  if (typeof raw.id !== "string" || !raw.id) return null;
  const name = cut(raw.name, 80);
  if (!name) return null;
  const categories = (Array.isArray(raw.categories) ? raw.categories : []).filter(
    (c): c is BriefingCategoryId =>
      (BRIEFING_CATEGORIES as readonly string[]).includes(c as string),
  );
  return {
    id: raw.id,
    name,
    description: cut(raw.description, 300),
    isDefault: raw.isDefault === true,
    apps: parseSources(raw.apps),
    categories,
    priority: PRIORITY_LEVELS.includes(raw.priority as string)
      ? (raw.priority as PriorityLevel)
      : "medium",
    frequency: (BRIEFING_FREQUENCIES as readonly string[]).includes(
      raw.frequency as string,
    )
      ? (raw.frequency as BriefingFrequency)
      : "daily",
    scheduleTime:
      typeof raw.scheduleTime === "string" &&
      /^\d{2}:\d{2}$/.test(raw.scheduleTime)
        ? raw.scheduleTime
        : "08:00",
    timezone: typeof raw.timezone === "string" && raw.timezone ? raw.timezone : "UTC",
    ...(typeof raw.runAt === "string" && raw.runAt ? { runAt: raw.runAt } : {}),
    enabled: raw.enabled !== false,
    nextRunAt:
      typeof raw.nextRunAt === "string" && raw.nextRunAt ? raw.nextRunAt : null,
    createdAt: typeof raw.createdAt === "string" ? raw.createdAt : "",
    ...(typeof raw.lastGeneratedAt === "string" && raw.lastGeneratedAt
      ? { lastGeneratedAt: raw.lastGeneratedAt }
      : {}),
  };
}
